import Foundation

// MARK: - Sensor Data Models

/// A single raw sensor sample captured from CoreMotion accelerometer + gyroscope.
/// Contains unfiltered accelerometer (g-force including gravity) and gyroscope (rad/s) data.
public struct SensorFrame: Sendable {
    /// Timestamp in seconds since the device booted (mach_absolute_time).
    public let timestamp: TimeInterval

    /// Raw accelerometer data (g-force, includes gravity vector).
    /// x = lateral (left/right), y = longitudinal (forward/back), z = vertical (up/down).
    public let accelerationX: Double
    public let accelerationY: Double
    public let accelerationZ: Double

    /// Raw gyroscope data (rad/s).
    /// x = pitch rate, y = roll rate, z = yaw rate.
    public let rotationRateX: Double
    public let rotationRateY: Double
    public let rotationRateZ: Double

    public init(
        timestamp: TimeInterval,
        accelerationX: Double,
        accelerationY: Double,
        accelerationZ: Double,
        rotationRateX: Double,
        rotationRateY: Double,
        rotationRateZ: Double
    ) {
        self.timestamp = timestamp
        self.accelerationX = accelerationX
        self.accelerationY = accelerationY
        self.accelerationZ = accelerationZ
        self.rotationRateX = rotationRateX
        self.rotationRateY = rotationRateY
        self.rotationRateZ = rotationRateZ
    }
}

// MARK: - Cadence Sample

/// A real-time cadence estimate produced by CadenceDetector.
public struct CadenceSample: Sendable {
    /// Estimated steps per minute.
    public let stepsPerMinute: Double
    /// Unix timestamp when this estimate was computed.
    public let timestamp: Date
    /// Confidence of the estimate (0.0–1.0).
    public let confidence: Double
    /// The time window over which the cadence was computed (seconds).
    public let windowDuration: TimeInterval

    public init(
        stepsPerMinute: Double,
        timestamp: Date = Date(),
        confidence: Double = 0.0,
        windowDuration: TimeInterval = 3.0
    ) {
        self.stepsPerMinute = stepsPerMinute
        self.timestamp = timestamp
        self.confidence = confidence
        self.windowDuration = windowDuration
    }
}

// MARK: - Gait Snapshot

/// A real-time gait metric snapshot produced by GaitAnalyzer.
public struct GaitSnapshot: Sendable {
    /// Vertical oscillation amplitude in cm (estimated from acceleration double-integration).
    public let verticalOscillationCm: Double
    /// Estimated ground contact time in milliseconds.
    public let groundContactTimeMs: Double
    /// Trunk lean angle in degrees (positive = forward lean).
    public let trunkLeanDegrees: Double
    /// Rolling mean cadence at time of snapshot.
    public let cadenceSPM: Double
    /// Unix timestamp when this snapshot was computed.
    public let timestamp: Date

    public init(
        verticalOscillationCm: Double = 0.0,
        groundContactTimeMs: Double = 0.0,
        trunkLeanDegrees: Double = 0.0,
        cadenceSPM: Double = 0.0,
        timestamp: Date = Date()
    ) {
        self.verticalOscillationCm = verticalOscillationCm
        self.groundContactTimeMs = groundContactTimeMs
        self.trunkLeanDegrees = trunkLeanDegrees
        self.cadenceSPM = cadenceSPM
        self.timestamp = timestamp
    }
}

// MARK: - Coach Prompt

/// A coaching prompt generated by AudioCoachEngine.
public struct CoachPrompt: Sendable {
    /// The text to be spoken.
    public let text: String
    /// Language code (e.g., "en", "zh-Hans", "nl").
    public let language: String
    /// Priority (0 = informational, 1 = suggestion, 2 = alert).
    public let priority: Int
    /// The metric category that triggered this prompt.
    public let category: CoachCategory

    public enum CoachCategory: String, Sendable {
        case cadence
        case verticalOscillation
        case groundContactTime
        case trunkLean
        case general
    }

    public init(
        text: String,
        language: String = "en",
        priority: Int = 0,
        category: CoachCategory = .general
    ) {
        self.text = text
        self.language = language
        self.priority = priority
        self.category = category
    }
}

// MARK: - Run Session State

/// State machine states for RunSessionManager.
public enum RunSessionState: String, Sendable {
    case idle
    case ready
    case running
    case paused
    case stopped
}

// MARK: - Run Session Configuration

/// Configuration for a live run session.
public struct RunSessionConfig: Sendable {
    /// Target cadence in steps per minute.
    public let targetCadenceSPM: Double
    /// Coaching language code.
    public let coachingLanguage: String
    /// Minimum interval between voice prompts (seconds).
    public let minPromptInterval: TimeInterval
    /// Sensor data buffer window in seconds (3–10).
    public let sensorWindowSeconds: TimeInterval
    /// Sensor sampling rate in Hz.
    public let samplingRate: Double

    public init(
        targetCadenceSPM: Double = 170,
        coachingLanguage: String = "en",
        minPromptInterval: TimeInterval = 15,
        sensorWindowSeconds: TimeInterval = 6,
        samplingRate: Double = 60
    ) {
        self.targetCadenceSPM = targetCadenceSPM
        self.coachingLanguage = coachingLanguage
        self.minPromptInterval = minPromptInterval
        self.sensorWindowSeconds = max(3, min(10, sensorWindowSeconds))
        self.samplingRate = samplingRate
    }
}
